name: flutter_demo_app
description: A new Flutter project for Android.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.11.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.7
  mobile_scanner: ^6.0.10
  barcode_scan2: ^4.2.4
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  google_mlkit_text_recognition: ^0.15.0
  google_sign_in: ^6.2.1
  # gallery_saver:
  #   path: ./gallery_saver
  # Optionally for document text recognition (OCR)
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
