// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFKCmkJe5VuhrGsltii8OVmQDqz6sEKk',
    appId: '1:409112611820:web:904ce0b38f27262d8c8ec9',
    messagingSenderId: '409112611820',
    projectId: 'scanner-app-c7d81',
    authDomain: 'scanner-app-c7d81.firebaseapp.com',
    storageBucket: 'scanner-app-c7d81.firebasestorage.app',
    measurementId: 'G-PSBDWCKRBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Op9KrP1jAppH3xBH3CnSuyrHPCdjzMo',
    appId: '1:409112611820:android:781fc3a163aa37aa8c8ec9',
    messagingSenderId: '409112611820',
    projectId: 'scanner-app-c7d81',
    storageBucket: 'scanner-app-c7d81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlurHVnOgTJdKd2balg9o6o3DBjpXXj8U',
    appId: '1:409112611820:ios:27533971cf01daaf8c8ec9',
    messagingSenderId: '409112611820',
    projectId: 'scanner-app-c7d81',
    storageBucket: 'scanner-app-c7d81.firebasestorage.app',
    androidClientId: '409112611820-cjjegec8hfq2l215nntpo33s47m6fbpq.apps.googleusercontent.com',
    iosClientId: '409112611820-7417uiub4a3sdn6bqlhfvq5ll5rh5rq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlurHVnOgTJdKd2balg9o6o3DBjpXXj8U',
    appId: '1:409112611820:ios:27533971cf01daaf8c8ec9',
    messagingSenderId: '409112611820',
    projectId: 'scanner-app-c7d81',
    storageBucket: 'scanner-app-c7d81.firebasestorage.app',
    androidClientId: '409112611820-cjjegec8hfq2l215nntpo33s47m6fbpq.apps.googleusercontent.com',
    iosClientId: '409112611820-7417uiub4a3sdn6bqlhfvq5ll5rh5rq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvFKCmkJe5VuhrGsltii8OVmQDqz6sEKk',
    appId: '1:409112611820:web:8a23ef34f63fd97e8c8ec9',
    messagingSenderId: '409112611820',
    projectId: 'scanner-app-c7d81',
    authDomain: 'scanner-app-c7d81.firebaseapp.com',
    storageBucket: 'scanner-app-c7d81.firebasestorage.app',
    measurementId: 'G-FQJXQQHTFG',
  );
}
